builds on opensuseTumbleWeed  but lauch fails due to ABI mismatch
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1002,STL containers,compatible with 2.8),
and wxNet used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8).
Aborted (core dumped)